/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package desktopapplication.databaseConn;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.regex.Pattern;
import java.util.regex.Matcher;
/**
 * 
 *
 * @author Shehara PC
 */
public class NewCustomer extends javax.swing.JFrame {

    /**
     * Creates new form NewCustomer
     */
    public NewCustomer() {
        initComponents();
        setLocationRelativeTo(null); 
        loadingLabel.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        first_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        last_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        country = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        phone_number = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nic = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        loadingLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(224, 247, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel1.setText("Personal Information");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 390, 30));

        jLabel2.setForeground(new java.awt.Color(38, 50, 56));
        jLabel2.setText("First Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        first_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_nameActionPerformed(evt);
            }
        });
        jPanel1.add(first_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 290, -1));

        jLabel3.setForeground(new java.awt.Color(38, 50, 56));
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        last_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_nameActionPerformed(evt);
            }
        });
        jPanel1.add(last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 290, -1));

        jLabel4.setText("Gender");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel5.setForeground(new java.awt.Color(38, 50, 56));
        jLabel5.setText("Country");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel6.setForeground(new java.awt.Color(38, 50, 56));
        jLabel6.setText("Address");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, -1));

        gender.add(male);
        male.setForeground(new java.awt.Color(38, 50, 56));
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        gender.add(female);
        female.setForeground(new java.awt.Color(38, 50, 56));
        female.setText("Female");
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        country.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "United States", "Canada", "Brazil", "Mexico", "Argentina", "United Kingdom", "Germany", "France", "Italy", "Spain", "Sri Lanka", "Australia", "Japan", "China", "India", "Russia", "South Africa", "Egypt", "Saudi Arabia", "South Korea", "New Zealand", " " }));
        country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryActionPerformed(evt);
            }
        });
        jPanel1.add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 180, -1));

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 290, -1));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));
        jPanel1.add(phone_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 290, -1));

        jLabel8.setForeground(new java.awt.Color(38, 50, 56));
        jLabel8.setText("Email");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 290, -1));

        jLabel9.setForeground(new java.awt.Color(38, 50, 56));
        jLabel9.setText("NIC/Passport Number");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));
        jPanel1.add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 290, -1));

        jLabel10.setForeground(new java.awt.Color(38, 50, 56));
        jLabel10.setText("Mobile Number");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        submit.setBackground(new java.awt.Color(38, 166, 154));
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Save");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 553, 130, 30));

        cancel.setText("Cancel");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 553, 120, 30));

        loadingLabel.setBackground(new java.awt.Color(255, 255, 255));
        loadingLabel.setForeground(new java.awt.Color(255, 255, 255));
        loadingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desktopapplication/images/loading.gif"))); // NOI18N
        loadingLabel.setMaximumSize(new java.awt.Dimension(40, 40));
        loadingLabel.setMinimumSize(new java.awt.Dimension(40, 40));
        jPanel1.add(loadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 80, 100));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desktopapplication/images/coconut-tree-4389028_1280 (1).png"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 800, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void last_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_last_nameActionPerformed

    private void countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
            clearForm();
    }//GEN-LAST:event_cancelActionPerformed

    private void clearForm() {
    first_name.setText("");
    last_name.setText("");
    gender.clearSelection();
    country.setSelectedIndex(0);
    address.setText("");
    phone_number.setText("");
    email.setText("");
    nic.setText("");
}
    
    
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        
        loadingLabel.setVisible(true);
        
        
        
    // Run DB save in a background thread
    new javax.swing.SwingWorker<Void, Void>() {
        @Override
        protected Void doInBackground() {
            
            String First_name = first_name.getText().trim();
            String Last_name = last_name.getText().trim();
            String Country = (String) country.getSelectedItem();
            String Address = address.getText().trim();
            String Phn_Number = phone_number.getText().trim();
            String Email = email.getText().trim();
            String NIC = nic.getText();

            String Gender = "";
            if (male.isSelected()) {
                Gender = "Male";
            } else if (female.isSelected()) {
                Gender = "Female";
                //a
            }

            if (!isValidEmail(Email)) {
                JOptionPane.showMessageDialog(NewCustomer.this, "Invalid Email !!!");
                return null;
            }

            try {
                Connection conn = DatabaseCon.getConnection();
                
                String sql = "INSERT INTO personal_data (first_name, last_name, gender, country, address, phone_number, email, nic) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, First_name);
                pstmt.setString(2, Last_name);
                pstmt.setString(3, Gender);
                pstmt.setString(4, Country);
                pstmt.setString(5, Address);
                pstmt.setString(6, Phn_Number);
                pstmt.setString(7, Email);
                pstmt.setString(8, NIC);

                int result = pstmt.executeUpdate();
                
                
                
                if (result > 0) {
                    JOptionPane.showMessageDialog(NewCustomer.this, "Customer saved successfully.");
                    clearForm();
                } else {
                  
                    JOptionPane.showMessageDialog(NewCustomer.this, "Failed to save customer.");
                }

                pstmt.close();
                conn.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(NewCustomer.this, "Fields Cannot be Empty");
                //e.printStackTrace();
            }

            return null;
        }

        @Override
        protected void done() {
            loadingLabel.setVisible(false);  // Hide loader after completion
        }
    }.execute();
        
    }//GEN-LAST:event_submitActionPerformed

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        new desktopapplication.DashBoard().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_cancelMouseClicked

    private void first_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_first_nameActionPerformed

    private static final String EMAIL_REGEX = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";

    public static boolean isValidEmail(String email) {
        Pattern pattern = Pattern.compile(EMAIL_REGEX);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewCustomer().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JButton cancel;
    private javax.swing.JComboBox<String> country;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField first_name;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField last_name;
    private javax.swing.JLabel loadingLabel;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField nic;
    private javax.swing.JTextField phone_number;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
